name: Generate Pacman

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman
        uses: Platane/snk@v3
        with:
          github_user_name: Choosenone-17
          outputs: |
            dist/pacman-contribution-graph.svg?palette=github-dark

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}